### ISSUE TITLE
App crashes when the CallClient constructor is called

### ISSUE THREAD

**Issue by radulescuserban** [Azure/Communication#330] opened 2021-07-07 14:58 UTC
**Describe the bug**
When calling the CallClient constructor the appliaction crashes

**To Reproduce**
1. call CallClient() constructor

**Expected behavior**
CallClient consturctor returns a new object and no crash is

**Logs**
 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tremend.reginamaria.debug, PID: 23780
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.tremend.reginamaria.debug-aBlgOCS17aXfAIBELtlOUQ==/base.apk", zip file "/system/framework/com.google.android.maps.jar"],nativeLibraryDirectories=[/data/app/com.tremend.reginamaria.debug-aBlgOCS17aXfAIBELtlOUQ==/lib/arm64, /data/app/com.tremend.reginamaria.debug-aBlgOCS17aXfAIBELtlOUQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libc++_shared.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.azure.android.communication.calling.CallClient.loadNativeLibraries(CallClient.java:223)
        at com.azure.android.communication.calling.CallClient.<clinit>(CallClient.java:232)
        at com.tremend.reginamaria.fragments.virtualconsultation.VirtualConsultationFragment.initViews(VirtualConsultationFragment.kt:79)
        at com.tremend.reginamaria.fragments.BaseFragment.onCreateView(BaseFragment.java:80)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Smartphone**
 - Device: Nexus 5X
 - OS: Android 8.1
 - Version: com.azure.android:azure-communication-calling:1.0.0-beta.10

**Additional context**
It is not a 100% repro rate. It seems to only happen when in the same application instance after I previously joined a teams conference and hanged up I try to enter in a new one (or rejoin the same).

**Comment by kagbakpem** [comment] 2021-07-15 13:57
Thanks for reporting this issue @radulescuserban. Can you please try one of the latest version of the Calling SDK and see if this is still reproduceable? [1.1.0-beta.1](https://search.maven.org/artifact/com.azure.android/azure-communication-calling/1.1.0-beta.1/aar)

**Comment by kagbakpem** [comment] 2021-07-18 22:30
@radulescuserban, we can't reproduce this issue in the upcoming version of the SDK. Please pick it up once it's available next week and let us know if this scenario still arise. Thanks

**Comment by kagbakpem** [comment] 2021-07-20 22:05
@radulescuserban, the latest SDK v1.2.0-beta.1 was published today and should have a fix for this. Please try it out and let us know if the issue persists.

**Closed by kagbakpem** 2021-07-20 22:05 UTC
Labels: Android, Bug, Calling, Teams interop
