### ISSUE TITLE
[iOS] CallAgent and CallClient dispose methods takes too long to execute

### ISSUE THREAD

**Issue by alexLipici-tmd** [Azure/Communication#339] opened 2021-07-15 08:44 UTC
**Describe the bug**
I integrated for my client Azure Communication Calling and Azure Communication Chat. For Chat, I'm using real time notification and I start it when the conference starts. When the conference ends, so when it returns from hangUp method, I call dispose methods for CallAgent and CallClient. Someone suggested me to call these methods also for stopping chat's real time notifications, because I had a problem on calling stopRealTimeNotifications method from Chat SDK (the app freezes for 1minute at least after that method is called). The main problem is that those dispose methods also takes too much time. Is a know behaviour and we should take care of a loading mechanism until the disposes are done?

**To Reproduce**
1. Create CallAgent and CallClient instances
2. Create ChatClient instance 
3. Register chat for real time notifications
4. After the conference is finished, call hangUp method to end the call
5. On hangUp finish closure call dispose methods for CallAgent and CallClient

**Expected behavior**
We expect that stopping calling those dispose methods last less time then now.

**Smartphone:**
 - Device: any iOS device

**Comment by mariusu-msft** [comment] 2021-07-15 21:51
@alexLipici-tmd do you happen to have a blog log file for the case where dispose takes a long time?

If you have already terminated the call, it is not supposed to take long

**Comment by raosanat** [comment] 2021-07-15 22:06
@alexLipici-tmd Can you please attach logs so that we can investigate the issue further ? Instructions are [here](https://docs.microsoft.com/en-us/azure/communication-services/concepts/troubleshooting-info?tabs=csharp%2Cios%2Cdotnet#tabpanel_4_ios). Also please make sure you reproduce in the latest build. Thanks.

**Comment by alexLipici-tmd** [comment] 2021-07-19 08:13
I attached the .blog file to the issue

[acs_sdk-0-204814378.blog.zip](https://github.com/Azure/Communication/files/6839084/acs_sdk-0-204814378.blog.zip)

**Comment by RinaRish** [comment] 2021-08-12 21:14
Thanks for attaching the log. We will take a look [AB#2545995](https://skype.visualstudio.com/SPOOL/_workitems/edit/2545995)

**Comment by mariusu-msft** [comment] 2021-09-24 00:24
@alexLipici-tmd this is expected because of time-bound operations that we are doing during clean-up.

It's expected that you always run this on a background thread, and do not block any UI operations behind this.

Can you try this and let us know how it goes?

**Comment by raosanat** [comment] 2021-11-18 20:31
Fixed in the latest release [v2.1.0-beta.1](https://github.com/Azure/Communication/releases/tag/v2.1.0-beta.1). 
Please re-open the bug if still reproducible, thanks.

**Closed by raosanat** 2021-11-18 20:31 UTC
Labels: Bug, Teams interop, iOS, ADO Linked, Waiting for Author
