### ISSUE TITLE
[iOS] Remote participant is still available after hangup/disconnect

### ISSUE THREAD

**Issue by devgokhan** [Azure/Communication#134] opened 2020-12-04 10:22 UTC
I am tried this with 2 iOS device. 
Both cameras was open I called hangup to leave from meeting in first user. First user locally disconnected and closed the meeting ViewController successfully. However second users sees that first user still in the meeting and camera is frozen. Anyway I hangup the second user then this user left from meeting and then I rejoined the meeting with second user. I see that first user still in the meeting but this time camera is off. 

This is happens sometimes. I tried this more than one time. It happened again after some successful tries. I saw that, when I pressed hangup everything getting weird. Hangup worked more longer. I mean viewController dismissed more time after. And I tried the rejoin, I was unable to rejoin again. Even if I close the viewController and dispose everything about the call it never fixes until I close the app and re-open again. Maybe I will open new ticket for this. This is another issue too. Reference: https://github.com/Azure/Communication/issues/135

**Comment by raosanat** [comment] 2020-12-04 10:27
Hi @devgokhan thanks for reporting the issue. But is it possible to attach the logs as well ? so that we can get information on the CallId and the order in which the API’s were called and other relevant information.

**Comment by devgokhan** [comment] 2020-12-04 10:34
Hi @raosanat, which logs do you mean? How can I send this logs to you how can I reach them?

**Comment by raosanat** [comment] 2020-12-04 10:42
Here are the instructions 

https://docs.microsoft.com/en-us/azure/communication-services/concepts/troubleshooting-info?tabs=csharp%2Cios%2Cdotnet#enable-and-access-call-logs

You can upload the logs to one drive and send us the link?

**Comment by devgokhan** [comment] 2020-12-04 12:28
Hi @raosanat, this problem happened in other device device that I didn't install the app via cable in debug mode, I was installed the app from TestFlight.. Because of that I am unable to see my app in the list of "Installed Apps".

I tried to face this error in my other second device, which I install with cable in debug mode, however it is not happened. But I remember that this problem happened in this device too, but I don't remember when. 

Anyway, I am sharing the logs which taken from second device that I explain. Here is the files: [https://drive.google.com/file/d/1bEhsEoBgcIJ47PxLuxhKozNE13NJ2uO8/view?usp=sharing](url)
This problem must be happened before in this device too but I am not sure if you can see the problem in last logs. Please let me know if see this in this logs.

**Comment by raosanat** [comment] 2020-12-04 21:53
Hi @devgokhan I tried to reproduce this with our internal app and i was not able to repro the issue. Following is what i did
1. Logged in from my 2 iPhones.
2. Both of them joined a group.
3. 1st user disconnects from the group call and 2nd user is still in the group call but does not see any video from the 1st user, as expected.
4. 1st user again joins the same group call and 2nd user can see that 1st user has successfully joined call and see the video from 1st user. 

There is no camera frozen on 2nd user or that 1st user is still in call in 2nd participant after 1st participant hanged up.

I see that you have multiple logs attached its difficult to co-relate which log belongs to the bug you have described above.

I would suggest reinstalling the app before you repro the issue OR give us the CallId of the call where you faced the issue and we can then map that with which log has the CallId.

**Comment by devgokhan** [comment] 2020-12-07 06:46
Hi. Actually I saw that twice time happened in my one device which is installed from TestFlight. However I am unable to send this device logs to you that's why explained it before above. But I will try to debug it via cable and try again. I hope problem happens again.

Anyway, this is my group id that I faced the issue; 
b132ac00-307f-11eb-8d17-735c039966b1
Problem happened 3 days ago, probably around 12 or 13 in GMT +3. I am not sure the time I forgot.

**Comment by devgokhan** [comment] 2020-12-07 08:00
Hi again. Today I tried again.
In my device first I removed the app and reinstall it again then I tried this problem not yet happened. I tried a lot of time but never reproduced.. 

Anyway, at the same time I was trying in simulator as second particapant. Problem occurred in simulator when I pressed hang up. Application is freezing second or third press of hang up (join close + join close + join close). 

Last logs must be about the error. Because after problem occurred I copied the logs.

I am sharing blog files of simulator from the location User/Library/Developer/CoreSimulator/Devices/Simulator Device Id/data/Containers/Data/Application/App Id/Library/Caches/
[Last Simulator Blog Files Drive Link](https://drive.google.com/file/d/1JSXCEiCgnKqQhUQY849A5OssT00qYU4x)

**Comment by raosanat** [comment] 2020-12-07 10:37
Hi @devgokhan Can you confirm that freeze is happening because the  completion handler on `Hangup` is not being invoked by the SDK ? I will try to reproduce this tomorrow, Thanks.

**Comment by devgokhan** [comment] 2020-12-07 13:22
Hi @raosanat  I am not sure it is happening in completion handler or not. But I can say it happens when hangup is called. I wanted to try again to find is it happening when the call method or is it happening after call inside completion handler, I tried again. Anyway, thankfully problem, that I firstly reported, happened again. I pressed hangup, then everything getting strange. And then I was unable to rejoin any meeting..

I am sharing logs with you. Last log acs_sdk-0-s4856891.blog, file updated 16:10 GMT +3 which is problem happened around this time. This happened in 14.2 iPhone 12 simulator.
[ACS Log 3 Drive Link](https://drive.google.com/file/d/1kyeKhVc5JsUpA5sRFeIs7LKMHlNquGav)

**Comment by raosanat** [comment] 2020-12-07 23:53
Thanks for the logs @devgokhan . We might have found out the issue that causes after `Hangup`. Some of the other issues you reported could be related because of the same bug. We will keep you updated. Also please do attach the logs for the bugs you report like this one. Thanks

**Comment by sankum-msft** [comment] 2020-12-08 01:43
@devgokhan For the time being, can you please try disposing `Renderer` objects before calling `hangup()` as a workaround for this issue?

**Comment by devgokhan** [comment] 2020-12-08 07:08
Hi @sankum-msft , actually I am doing this already?

`
private func close() {
      print("Meeting -> Closing..")
       if self.remoteParticipants.count > 0 {
           for item in self.remoteParticipants {
               item.delegate = nil
           }
       }
       self.remoteParticipants.removeAll()
       self.call?.delegate = nil
       self.timer?.invalidate()
       self.timer = nil
       self.targetRemoteParticipantView?.dispose()
       self.localVRendererView?.dispose()
       self.localRenderer?.dispose()
       self.remoteRenderer?.dispose()
       
       if let call = self.call {
           print("Meeting -> Hangup starting..")
           call.hangup(options: HangupOptions(), completionHandler: { [weak self] (error) in
               if let error = error {
                   Utils.log("Meeting -> Hangup error: \(error.localizedDescription)")
               }
               Utils.log("Meeting -> Hangup completed!")
               Utils.log("Meeting -> Will dismiss..")
               self?.dismiss()
           })
       } else {
           print("Meeting -> Will dismiss - there is no call avaible")
           self.dismiss()
       }
   }
`

**Comment by sankum-msft** [comment] 2020-12-16 20:21
We've identified a bug in `Renderer` disposal where video object is not cleaned up properly if disposed too early. This snowballs into call connectivity issues as a thread is waiting for that to be cleaned up. I've opened an internal bug AB#2337884 to get it fixed.

**Comment by sankum-msft** [comment] 2021-01-08 02:48
This issue is fixed in the latest SDK release. Please reopen this bug if you are still having issues.

**Closed by sankum-msft** 2021-01-08 02:48 UTC
Labels: ADO Linked, Calling, iOS
