### ISSUE TITLE
App crashes when hanging up from a teams conference room

### ISSUE THREAD

**Issue by radulescuserban** [Azure/Communication#331] opened 2021-07-07 15:27 UTC
**Describe the bug**
When leaving from a teams conference applcation crashes after a variable number of seconds (had up to 1 minute)

**To Reproduce**
1) enter a teams conference via URL
2) hang up from the call

**Logs**
This is the only thing that I can find in logcat that seems to be related to this crash (I don't get any fatal exceptions)
A/libc: Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7c041149dc in tid 19090 (pool-32-thread-), pid 15632 (ginamaria.debug)

**Smartphone**
Device: Nexus 5X
OS: Android 8.1
Version: com.azure.android:azure-communication-calling:1.0.0-beta.10

**Additional context**
It is not a 100% repro rate

**Comment by kagbakpem** [comment] 2021-07-07 15:56
Thanks for reporting this issue, @radulescuserban.

Can you please make sure you're able to repro this issue on the latest version of the SDK [here](https://search.maven.org/artifact/com.azure.android/azure-communication-calling/1.1.0/aar)?

**Comment by radulescuserban** [comment] 2021-07-09 10:49
hey, I just updated the SDK to the latest beta version 1.1.0-beta.1 (I need the beta versions for the teams interoperability). I will report here if the same crash still happens.

**Comment by radulescuserban** [comment] 2021-07-09 14:38
I just encountered the crash:
 A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x6c in tid 13882 (HeapTaskDaemon), pid 13860 (ginamaria.debug)
This time it seems to be another error.

Here is the acs_sdk log file.
[acs_sdk-0-s1293427023.zip](https://github.com/Azure/Communication/files/6792118/acs_sdk-0-s1293427023.zip)

**Comment by kagbakpem** [comment] 2021-07-15 13:58
Thanks for the logs, @radulescuserban. We'll get back to you by EOD.

**Comment by kagbakpem** [comment] 2021-07-18 22:29
@radulescuserban, we can't reproduce this issue in the upcoming version of the SDK. Please pick it up once it's available next week and let us know if this scenario still arise. Thanks

**Comment by kagbakpem** [comment] 2021-07-20 22:04
@radulescuserban, the latest SDK [v1.2.0-beta.1](https://search.maven.org/artifact/com.azure.android/azure-communication-calling/1.2.0-beta.1/aar) was published today and should have a fix for this. Please try it out and let us know if the issue persists.

**Closed** 2021-07-20 22:04 UTC
Labels: Android, Bug, Calling, Teams interop
