### ISSUE TITLE
[BUG] Audio is not working after incoming alarm

### ISSUE THREAD

**Issue by dudeck** [Azure/Communication#461] opened 2022-05-09 09:00 UTC
**Describe the bug**
During the Teams meeting when clock alarm income audio on meeting stops working (participant is not hearing others and otherwise) even when alarm is dismissed.

***Exception or Stack Trace***
```
2022-05-05 11:25:00.954 0000000101058580 INFO UTILITIES CCallsManager.mm:82 CCallsManagerAVAudioSessionHandler:beginInterruption

2022-05-05 13:25:04.834525+0200 Runner[5720:2561854] [aurioc]            AURemoteIO.cpp:1123  failed: 1701737535 (enable 2, outf< 1 ch,  16000 Hz, Int16> inf< 1 ch,  16000 Hz, Int16>)

2022-05-05 13:25:04.942119+0200 Runner[5720:2561854] [aurioc]            AURemoteIO.cpp:1123  failed: 1701737535 (enable 2, outf< 1 ch,  16000 Hz, Int16> inf< 1 ch,  16000 Hz, Int16>)

2022-05-05 13:25:04.951586+0200 Runner[5720:2561852] [aurioc]            AURemoteIO.cpp:1123  failed: 1701737535 (enable 3, outf< 1 ch,  16000 Hz, Int16> inf< 1 ch,  16000 Hz, Int16>)

2022-05-05 13:25:05.069057+0200 Runner[5720:2561852] [aurioc]            AURemoteIO.cpp:1123  failed: 1701737535 (enable 3, outf< 1 ch,  16000 Hz, Int16> inf< 1 ch,  16000 Hz, Int16>)

2022-05-05 11:25:05.813 0000000101058580 INFO UTILITIES CCallsManager.mm:100 CCallsManagerAVAudioSessionHandler:endInterruption
```

**To Reproduce**
1. Set incomming alarm in clock system app on iPhone.
2. Connect to Teams meeting with enabled microphones on both sides.
3. Wait for alarm.
4. Dismiss alarm.
5. Audio is not working.

**Expected behavior**
After dismissing alarm audio should work again.

**Setup (please complete the following information):**
 - OS: iOS 14.7.1 iPhone 6s Plus
 - IDE : XCode
 - Version of the Library used: AzureCommunicationCalling (2.0.0)

```
PODS:
    AzureCommunicationCalling (2.0.0):
        AzureCommunicationCommon (~> 1.0.2)
    AzureCommunicationCommon (1.0.3)
```

**Comment by dudeck** [comment] 2022-05-26 07:36
Yes, we integrated our app with CallKit. That's great that you're working on this feature, we'll use it as soon as it's ready and stable for our purposes.

Although we have a similar issue after a phone call (with a different error code - 561017449), this case is about alarm notification.

I hope you're able to reproduce this issue.

**Comment by gaobob-msft** [comment] 2023-09-07 16:04
@dudeck are you still able to reproduce the issue using the latest iOS SDK? I will close the issue for now since it's over a year old. Please re-open the issue if you can still repro with iOS SDK 2.6.1

**Closed by gaobob-msft** 2023-09-07 16:04 UTC
Labels: Needs: triage :mag:, Question, Communication, customer-reported
