### ISSUE TITLE
Token Generation RestError Unsupported api version Engountered an error  RestError: The HTTP resource that matches the request URI 'https://52.168.169.1/identities' does not support the API version '2020-07-20-preview2'. 

### ISSUE THREAD

**Issue by xtianus79** [Azure/Communication#159] opened 2021-01-14 15:39 UTC
**Describe the bug**

When running the generate user token using the const { CommunicationIdentityClient } = require('@azure/communication-administration'); package the following error occurs and all of my applications are broken because I cannot generate a user token. 

The call below is particularly failing at this point:

let userResponse = await identityClient.createUser(); 
Engountered an error  RestError: The HTTP resource that matches the request URI 'https://52.168.169.1/identities' does not support the API version '2020-07-20-preview2'. 

**Expected behavior**
a token to be generated. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Logs**
<br/>Please attach the logs or share the callId. Instructions could be found [here](https://docs.microsoft.com/en-us/azure/communication-services/concepts/troubleshooting-info?tabs=csharp%2Cjavascript%2Cdotnet)

**Comment by ddematheu2** [comment] 2021-01-14 23:50
Thank you for reporting the issue, we are currently investigating. Will have an update soon.

**Comment by smartcat32** [comment] 2021-01-16 19:09
I'm still seeing this issue with the JS script, and as of yesterday now the C# app is failing too.

JS Script: 
```
Azure Communication Services - Access Tokens Quickstart
Encountered and error
RestError: Denied by the resource provider. 
 {
  "name": "RestError",
  "code": "Denied",
  "statusCode": 401,
```

C# app:
```
Azure Communication Services - Access Tokens Quickstart
Unhandled exception. Azure.RequestFailedException: Service request failed.
Status: 401 (Unauthorized)

Content:
{"error":{"code":"Denied","message":"Denied by the resource provider."}}

Headers:
Transfer-Encoding: chunked
MS-CV: REDACTED
Strict-Transport-Security: REDACTED
x-ms-client-request-id: REDACTED
X-Processing-Time: REDACTED
X-Azure-Ref: REDACTED
Date: Sat, 16 Jan 2021 REDACTED GMT
Content-Type: application/json

   at Azure.Communication.Administration.CommunicationIdentityRestClient.CreateAsync(CancellationToken cancellationToken)
   at Azure.Communication.Administration.CommunicationIdentityClient.CreateUserAsync(CancellationToken cancellationToken)
   at AccessTokensQuickstart.Program.Main(String[] args) in /Users/kaiser/Projects/kp/AccessTokensQuickstart/Program.cs:line 21
   at AccessTokensQuickstart.Program.<Main>(String[] args)
```

**Comment by ddematheu2** [comment] 2021-01-19 18:57
@RezaJooyandeh can you help here? Seems like they are still seeing an issue (different than the one we fixed last week https://github.com/Azure/Communication/issues/160)

**Comment by RezaJooyandeh** [comment] 2021-01-19 19:30
@smartcat32  you seem to be having a separate authentication issue. You might need to double check your connection string with the portal to ensure that you have an up-to-date one.

**Comment by RezaJooyandeh** [comment] 2021-01-19 19:32
Duplicate of #160

**Closed by RezaJooyandeh** 2021-01-19 19:32 UTC
Labels: Bug
