### ISSUE TITLE
[Feature request] ACS Chat active/inactive threads

### ISSUE THREAD

**Issue by GuidoNeele** [Azure/Communication#345] opened 2021-07-23 12:27 UTC
As ACS chat is currently implemented there are two type of threads:
1. Threads in which the user is a participant (active threads)
2. Threads in which the user is no longer a participant (inactive threads)

ACS doesn't make a distinction between the two when you request the threads via {endpoint}/chat/threads?maxPageSize={maxPageSize}&startTime={startTime}&api-version=2021-03-07 (https://docs.microsoft.com/en-us/rest/api/communication/chat/chat/list-chat-threads). Threads are returned as if the user is participating in them. It would be useful if the thread would indicate if the user is actively participating in the thread or not. The only way to know if the thread is active is by checking the participants list. If it errors out with a 403 then we know the user isn't a participant anymore. 

It would also be helpful if there was a parameter that could be used to filter the threads. For example:
- {endpoint}/chat/threads?maxPageSize={maxPageSize}&startTime={startTime} (Active & inactive threads)
- {endpoint}/chat/threads?maxPageSize={maxPageSize}&startTime={startTime}&active=true (Only active threads)
- {endpoint}/chat/threads?maxPageSize={maxPageSize}&startTime={startTime}&active=false (Only inactive threads)

**Comment by angiurgiu** [comment] 2021-07-29 00:04
The fact that Inactive threads are returned is by design, since users still have access to the message history of threads they've left

The filtering parameter isn't feasible for ACS as it would break pagination, since the underlying service doesn't support it.

@ashwinder and @juancamilor to determine if we want to update the returned ThreadInfo to have a new parameter indicating the membership state

**Comment by btmpn** [comment] 2021-08-05 08:38
We had a similar problem. There seems to be no way to find out if the requesting user is still part of a chat thread.
Since it is no longer wanted to post feature requests here on github, I created a post in Azure Feedback portal:

https://feedback.azure.com/forums/934536-azure-communication-services/suggestions/43829745-acs-chat-sdk-chatclient-listchatthreads-should-be

**Comment by angiurgiu** [comment] 2021-08-11 23:13
Closing this feature request here, and we will monitor requests for this feature in the dedicated portal.

**Closed by angiurgiu** 2021-08-11 23:13 UTC
Labels: Bug
