### ISSUE TITLE
At the end of the conference we get an ANR ( App not responding) , the app freezes

### ISSUE THREAD

**Issue by bogdanmunteanu** [Azure/Communication#390] opened 2021-09-29 14:10 UTC
**Describe the bug**
At the end of the conference we get an ANR ( App not responding) , the app freezes
We are hanging up using the method :
```
   call?.hangUp()?.get()
```

**To Reproduce**
Enter the conference and attempt to exit.

**Expected behavior**
The conference should exit. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Nexus 5
 - OS: Android 8.1
 - SDK Version : 1.2.0-beta.2

**Additional context**
Reproduction rate 80% .

**Comment by bogdanmunteanu** [comment] 2021-09-29 14:22
[27_aug_acs_sdk-0-s1148191003.blog.zip](https://github.com/Azure/Communication/files/7252703/27_aug_acs_sdk-0-s1148191003.blog.zip)
Logs for the ANR

**Comment by mariusu-msft** [comment] 2021-09-29 14:56
@bogdanmunteanu thanks for the report.

Can you please let us know if you are doing hangUp on a background thread?

.get() will be blocking the current thread, so it's not indicated for .get() to be called on the UI thread.

**Comment by bogdanmunteanu** [comment] 2021-09-29 15:16
> @bogdanmunteanu thanks for the report.
> 
> Can you please let us know if you are doing hangUp on a background thread?
> 
> .get() will be blocking the current thread, so it's not indicated for .get() to be called on the UI thread.

We did that already. We didn't, however , test the newer versions of the SDK (1.2.0 stable and 1.2.1- beta1). We'll test with that and keep this ticket updated.

**Comment by mariusu-msft** [comment] 2021-09-29 15:43
`We did that already. `

@bogdanmunteanu  what was the outcome of this ^ - are you still hitting the ANR after using background thread to hangUp?

**Comment by bogdanmunteanu** [comment] 2021-09-30 06:52
> `We did that already. `
> 
> @bogdanmunteanu what was the outcome of this ^ - are you still hitting the ANR after using background thread to hangUp?

Yes . we are still getting the ANR . But we need to test with the newer version of the SDK to see if the issue is still present. I will take care of this and update the ticket with newer information if/when it's available.

**Comment by mariusu-msft** [comment] 2021-09-30 06:57
Thanks @bogdanmunteanu

We have tried reproducing, and could not reproduce with the quickstart samples. We are investigating the logs and will reply back soon.

If you able to capture a process dump during ANR, please let us know and send us an email to get the proc dump from you

**Comment by mariusu-msft** [comment] 2021-11-18 09:47
This should be fixed with latest release of Android Beta SDK. Closing.

@bogdanmunteanu please reopen if you continue to encounter this

**Closed by mariusu-msft** 2021-11-18 09:47 UTC
Labels: Bug, Needs: triage :mag:

**Comment by bogdanmunteanu** [comment] 2021-11-18 12:29
Yes , confirming the fix. Cannot reproduce it anymore :)
