### ISSUE TITLE
[iOS] ACSRendererView is blank when not added to the window right away

### ISSUE THREAD

**Issue by ryanespiritu** [Azure/Communication#132] opened 2020-12-03 21:17 UTC
**Describe the bug**
Creating an `ACSRendererView` but not adding it to the window right away results in a blank rendering for the view when it is eventually added to the window.

**To Reproduce**
1. Create an `ACSRendererView`
2. Do not add the view to the window right away (I delayed ~5s in my local testing)
3. Add the `ACSRendererView` to the window
4. Observe that the `ACSRendererView` stream is blank

**Expected behavior**
I expected an `ACSRendererView` to behave like a `UIView` and layout properly once it's added to the window (even if there is a delay in this).

**Additional context**
I came across this while trying to simulate a scenario where a consumer of this SDK may want to create `ACSRendererView`'s in advance but not add them to the view hierarchy right away. I know this is a bit of an edge-case but figured it was still worth mentioning, thanks!

**Comment by sankum-msft** [comment] 2021-01-07 02:09
I have a local repro of the bug. This probably has the same root cause as #127. Investigating.

**Comment by sankum-msft** [comment] 2021-01-07 02:13
@ryanespiritu This bug is only for rendering `LocalVideoStream`, right? I was not able to repro this for `RemoveVideoStream`.

**Comment by ryanespiritu** [comment] 2021-01-07 18:00
Thanks for looking into things. Yes, I'm only able to reproduce for the `LocalVideoStream`

**Comment by sankum-msft** [comment] 2021-01-08 04:07
Confirmed that root cause is same as #127. Fix is tracked by AB#2325318.

**Comment by sankum-msft** [comment] 2021-01-13 01:36
Fix has been merged for this issue and will be included in the next release.

**Comment by sankum-msft** [comment] 2021-02-16 23:27
Closing this issue as the fix is included in [1.0.0-beta.8](https://github.com/Azure/Communication/releases/tag/v1.0.0-beta.8) release of the ACS iOS SDK. Please re-open if issue persists for you after the upgrade.

**Closed by sankum-msft** 2021-02-16 23:27 UTC
Labels: ADO Linked, Calling, Video, iOS
